sudo: required
dist: trusty

branches:
  only:
  - master

language: go
go:
  - 1.8.x

env:
- VIPS_VERSION=8.5.5

before_install:
- ./packaging/install-vips.sh

install:
- go get github.com/tools/godep
- go get github.com/wadey/gocovmerge
- godep restore
script:
- ./.travis/test.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
